## create tensor and numpy array

In [0]:
import numpy as np
import torch

In [29]:
a = np.array(1)
b = torch.tensor(1)
print(a)
print(b)
print(type(a))
print(type(b))

1
tensor(1)
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


## Mathematical operations

In [30]:
a = np.array(1)
b = np.array(2)
print(a,b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

1 2
3
-1
2
0.5


In [31]:
a = torch.tensor(1)
b = torch.tensor(2)
print(a,b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor(1) tensor(2)
tensor(3)
tensor(-1)
tensor(2)
tensor(0)


## Matrix Initialization

In [32]:
a = np.zeros((3,3))
print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


In [33]:
a = torch.zeros(3,3)
print(a)
print(a.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])


In [34]:
a = np.random.randn(3,3)
print(a)

[[ 0.0811438  -0.27519602  0.34558378]
 [ 0.01311694 -0.12339435 -1.75118382]
 [ 0.25507521 -0.30699684  0.32334483]]


In [35]:
a = torch.randn(3,3)
print(a)

tensor([[ 0.2480,  0.1559, -0.1607],
        [ 0.4172,  1.0004,  0.6008],
        [ 0.1098, -0.8411, -0.2908]])


### Matrix Operations

In [36]:
a = np.random.randn(3,3)
b = np.random.randn(3,3)
print(a,b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(np.transpose(a))

[[ 0.18542855 -0.33669337 -0.75666249]
 [ 0.87608095 -0.22289001  0.87344617]
 [-0.38544108 -0.24976049  1.90991538]] [[-0.72621517  0.25546997 -0.25973501]
 [ 0.31842906 -1.88348096  0.31448066]
 [ 0.20800256  0.02063868  0.88443762]]
[[-0.54078662 -0.0812234  -1.0163975 ]
 [ 1.19451001 -2.10637097  1.18792683]
 [-0.17743852 -0.22912181  2.794353  ]]
[[ 0.91164372 -0.59216334 -0.49692749]
 [ 0.55765189  1.66059095  0.55896551]
 [-0.59344363 -0.27039917  1.02547776]]
[[-0.13466103 -0.08601505  0.19653174]
 [ 0.27896963  0.41980909  0.27468193]
 [-0.08017273 -0.00515473  1.68920101]]
[[ -0.25533555  -1.31793719   2.91320954]
 [  2.75125943   0.1183394    2.77742414]
 [ -1.85305934 -12.10157181   2.15946873]]
[[ 0.18542855  0.87608095 -0.38544108]
 [-0.33669337 -0.22289001 -0.24976049]
 [-0.75666249  0.87344617  1.90991538]]


In [37]:
a = torch.randn(3,3)
b = torch.randn(3,3)
print(a,b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(torch.t(a))

tensor([[-0.1480, -0.9266, -1.3256],
        [ 1.4205, -0.4190,  0.3577],
        [-0.1508,  0.1087, -0.1135]]) tensor([[-1.3955, -1.3766, -0.0968],
        [-0.9656,  0.2583,  0.6799],
        [-0.3886, -0.5134, -0.1260]])
tensor([[-1.5435, -2.3033, -1.4225],
        [ 0.4549, -0.1607,  1.0376],
        [-0.5394, -0.4047, -0.2395]])
tensor([[ 1.2476,  0.4500, -1.2288],
        [ 2.3861, -0.6774, -0.3222],
        [ 0.2378,  0.6221,  0.0125]])
tensor([[ 0.2065,  1.2757,  0.1283],
        [-1.3717, -0.1082,  0.2432],
        [ 0.0586, -0.0558,  0.0143]])
tensor([[ 0.1060,  0.6731, 13.6938],
        [-1.4711, -1.6219,  0.5261],
        [ 0.3881, -0.2117,  0.9010]])
tensor([[-0.1480,  1.4205, -0.1508],
        [-0.9266, -0.4190,  0.1087],
        [-1.3256,  0.3577, -0.1135]])


### Reshaping Tensors

In [38]:
torch.manual_seed(2)
a = torch.randn(3,2)
print(a)
print(a.shape)
print(a.reshape(1,6))

tensor([[ 0.3923, -0.2236],
        [-0.3195, -1.2050],
        [ 1.0445, -0.6332]])
torch.Size([3, 2])
tensor([[ 0.3923, -0.2236, -0.3195, -1.2050,  1.0445, -0.6332]])


### concat tensors

In [39]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
print(torch.cat((a,b)))
print(torch.cat((a,b),dim=1))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [40]:
a = np.array([1,2,3,4])
b = torch.from_numpy(a)
print(b)

tensor([1, 2, 3, 4])


## Common PyTorch Modules
### Autograd Module
PyTorch uses a technique called automatic differentiation. It records all the operations that we are performing and replays it backward to compute gradients. This technique helps us to save time on each epoch as we are calculating the gradients on the forward pass itself.

The autograd module helps us to compute the gradients in the forward pass itself which saves a lot of computation time of an epoch


In [41]:
a = torch.ones((2,2),requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [42]:
b = a + 5
c = b.mean
print(b,c)
#c.backward()
#print(a.grad)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>) <built-in method mean of Tensor object at 0x7fc27247f0d8>


### Optim Module
The Optim module in PyTorch has pre-written codes for most of the optimizers that are used while building a neural network. We just have to import them and then they can be used to build models.

Let’s see how we can use an optimizer in PyTorch:

In [0]:
from torch import optim

# adam
# adam = optim.Adam(model.parameters(),lr = learning_rate)

# sgd
# sgd = optim.sgd(model.parameters(), lr = learning_rate)

Above are the examples to get the ADAM and SGD optimizers. Most of the commonly used optimizers are supported in PyTorch and hence we do not have to write them from scratch. Some of them are:

*   SGD   
*   Adam
*   Adadelta
*   Adagrad
*   AdamW
*   SparseAdam
*   Adamax
*   ASGD (Averaged Stochastic Gradient Descent)
*   RMSprop
*   Rprop (resilient backpropagation)







# nn Module
The autograd module in PyTorch helps us define computation graphs as we proceed in the model. But, just using the autograd module can be low-level when we are dealing with a complex neural network.

In those cases, we can make use of the nn module. This defines a set of functions, similar to the layers of a neural network, which takes the input from the previous state and produces an output.

## Building a Neural Network from Scratch in PyTorch

In [44]:
# Input tensor
x = torch.Tensor([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#output
y = torch.tensor([[1],[1],[0]])

print(x,'\n')
print(y)

tensor([[1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 1., 0., 1.]]) 

tensor([[1],
        [1],
        [0]])


Next, we will define the sigmoid function which will act as the activation function and the derivative of the sigmoid function which will help us in the backpropagation step:

In [0]:
#sigmoid function
def sigmoid(x):
  return 1/(1 + torch.exp(-x))

#derivative of sigmoid function
def derivatives_sigmoid(x):
  return x*(1-x)

Next, initialize the parameters for our model including the number of epochs, learning rate, weights, biases, etc.:

In [0]:
#variable initialization
epoch = 7000
lr = 0.1
inputlayernurons = x.shape[1]
hiddenlayernurons = 3
outputnurons = 1

#weight and bias initialization
wh = torch.randn(inputlayernurons,hiddenlayernurons).type(torch.FloatTensor)
bh = torch.randn(1,hiddenlayernurons).type(torch.FloatTensor)
wout = torch.randn(hiddenlayernurons,outputnurons)
bout = torch.randn(1,outputnurons)


Here we have randomly initialized the weights and biases using the .randn() function which we saw earlier. Finally, we will create a neural network. I am taking a simple model here just to make things clear. There is a single hidden layer and an input and an output layer in the model:

In [0]:
for i in range(epoch):
  #forward propogation
  hidden_layer_input1 = torch.mm(x,wh)
  hidden_layer_input = hidden_layer_input1 + bh
  hidden_layer_activations = sigmoid(hidden_layer_input)

  outputlayer_input1 = torch.mm(hidden_layer_activations,wout)
  outputlayer_input = outputlayer_input1 + wout
  output = sigmoid(outputlayer_input1)

  #backpropogation
  E = y - output
  slope_output_layer = derivatives_sigmoid(output)
  slope_hidden_layer = derivatives_sigmoid(hidden_layer_activations)
  d_output = E * slope_output_layer
  error_at_hidden_layer = torch.mm(d_output, wout.t())
  d_hiddenlayer =  error_at_hidden_layer * slope_hidden_layer
  wout += torch.mm(hidden_layer_activations.t(),d_output) * lr
  bout += d_output.sum() * lr
  wh   += torch.mm(x.t(),d_hiddenlayer) * lr
  bh   += d_output.sum() * lr

In [48]:
print(y,'\n')
print(output,'\n')

tensor([[1],
        [1],
        [0]]) 

tensor([[0.9647],
        [0.9770],
        [0.0314]]) 



So, the target is 1, 1, 0 and the predicted values from the model are 0.98, 0.97 and 0.03. Not bad at all!

In [0]:
print(train.shape)